### ISSUE TITLE
Remove falsy tests which don't align with interface specification

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs-base/data-model#11]
The interface specification clearly documents that it expects, w.r.t. the `other` argument, a Term for `Term#equals(Term other)` and a Quad for `Quad#equal(Quad other)`. The behavior for unexpected types is not defined, i.e., whether it should return false or throw an Error: [#132](https://github.com/rdfjs/representation-task-force/issues/132) and [#133](https://github.com/rdfjs/representation-task-force/issues/133).

Until these issues are resolved, the falsy tests in this suite should not make assumptions about undefined behavior. Let's get this suite aligned with the specification for now and table such tests until we can come to a decision about the interface.

**Comment by RubenVerborgh** [comment]
We should probably just move faster with https://github.com/rdfjs/representation-task-force/issues/132 and https://github.com/rdfjs/representation-task-force/issues/133

**Comment by bergos** [comment]
Obsoleted by spec update
