### ISSUE TITLE
read-only dataset

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/data-model#20]
I would like to propose the introduction a read-only dataset where all the mutations are forbidden.

This would be useful when a library wants to pass a dataset to a 3rd party but prevent impure, in-place modification.

I was thinking of a method which would return a read-only wrapper of itself:

```ts
interface DatasetCore {
  readonly(): DatasetCore
}
```

But without changing the originating object.

```js
const writable = dataset()
const readonly = writable.readonly()

// OK
writable.add(quad)

// not OK
readonly.add(quad)
```

**Comment by rubensworks** [comment]
Sounds like a good idea. I would add a subset of the `DatasetCore` interface for this, something like `DatasetCoreImmutable`, which doesn't expose mutation methods.

**Comment by tpluscode** [comment]
I just ran this through my colleagues and @martinmaillard just made me realise that the readonly version must not be a copy. Any changes to the original should be immediately reflected in the readonly version:

```js
const original = $rdf.dataset()
const readonly = original.readonly()

expect(readonly.size).toEqual(0)

original.add($rdf.quad())

expect(readonly.size).toEqual(1)
```

**Comment by l00mi** [comment]
* Lets first do an implementation to for a specific use-case.
* If we have a proposition we can see if necessary to add this to the spec.
* Then it will go to rdfjs-base?

**Comment by bergos** [comment]
@tpluscode @rubensworks If you want to continue the discussion, please open an issue in the [dataset specification repo](https://github.com/rdfjs/dataset-spec).
