### ISSUE TITLE
Add Typescript user-defined Type Guards

### ISSUE THREAD

**Issue by alexkreidler** [rdfjs-base/data-model#22]
Right now I have some code that looks like this:
```ts
const b = {
    s: Term
    p: Term
    o: Term
}
if (
    b.s.termType != "NamedNode" &&
    b.s.termType != "BlankNode"
) {
    return
}
if (b.p.termType != "NamedNode") {
    return
}

if (
    b.p.termType != "NamedNode" ||
    b.p.termType != "BlankNode" ||
    b.p.termType != "Literal"
) {
    return
}
quad(b.s, b.p, b.o, defaultGraph)
```

It's getting pretty hairy and I doubt I'm doing everything correctly. DeMorgans laws!! It would be awesome if I could write things like:
```ts
if (!(isBlankNode(b.s) || isNamedNode(b.s))) {
    return
}
```
and have Typescript infer the proper type of `b.s` (`BlankNode | NamedNode`) in subsequent accesses.

See: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards.

This repo might not be the right place to raise this issue as it's not written in TS, in which case I'll open an issue in `@types`.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29836 for more background.

I also wonder if there's a specific reason if this library isn't written directly in Typescript. No particular benefits come to mind, so I'd appreciate if someone could give some insight.

Thanks all for a nice RDF/JS ecosystem!

**Comment by bergos** [comment]
This implementation just covers the spec and the spec says:

> We don't define any validation of given values (e.g. IRI, URI, CURIE).

The spec is not explicitly about your use case, but we had two reasons to add it:

- Performance: If another part of your code does already the validation there is no need to check it again in the data model.
- Flexibility: The RDF spec may set constraints on the data, but maybe there are some cases like intermediate data or algorithms, where you don't want to follow it very strictly.

The spec also says:

> Implementations that apply validation should make this fact clear in their documentation.

So you are always free to wrap the data model and validation to it.

> This repo might not be the right place to raise this issue as it's not written in TS, in which case I'll open an issue in @types.

Yes, for TS related stuff, that is the better place to discuss it. You could also check the RDF/JS Gitter channel.

> I also wonder if there's a specific reason if this library isn't written directly in Typescript.

- Being as close as possible to the spec (as far as I know TS still doesn't support WebIDL)
- Every TS developer should know JS, but it's not the other way round, so using JS lowers the barrier and doesn't require additional tools

@alexkreidler Please close the issue, if I covered all of your questions and there are no follow up questions.
