### ISSUE TITLE
Depricate rdf-data-model

### ISSUE THREAD

**Issue by jeswr** [rdfjs-base/data-model#36]
The `rdf-data-model` package is still released on npm at the `1.0.0` version and has not been deprecated.

I for one sometimes accidentally use it instead of `@rdfjs/data-model` - especially because there are some docs floating around that still reference it such as that for https://www.npmjs.com/package/rdf-string. It would be nice to get a warning from npm when making such a mistake,

**Comment by bergos** [comment]
All versions of `rdf-data-model` are deprecated now, with the info to switch to `@rdfjs/data-model`.
