### ISSUE TITLE
Remove deep clone comparison

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs-base/data-model#41]
I don't think these comparisons are required by the spec? Impls may prefer to cache the components of a quad. I think it should be up to user if they want to do a deep clone.

https://github.com/rdfjs-base/data-model/blob/c9c388f891e87ae8e690cd1b87f4ce2bfe9774ba/test/fromQuad.test.js#L22-L25

**Comment by bergos** [comment]
You are right. I would expect that one calls the method to get an object that has all features of the factory (Term + Quad), but the spec leaves that open.

You want to create a PR?

**Comment by bergos** [comment]
fixed in #44
